### PR TITLE
Updated plugins to latest versions

### PR DESCRIPTION
**Pull request by InfoSec812**
#### What does this PR do?
Updates Jenkins plugins to the latest versions

#### Is there a relevant Issue open for this?
CIL-1031

#### Are there any other relevant resources that should be reviewed as well?
N/A

#### Who would you like to review this?
/cc @mdanter @sherl0cks @oybed @logandonley

### CODE REVIEW

**Comment by InfoSec812** [comment]
I did not do anything to explicitly remove the Blue Ocean plugins... Not sure why they are not showing up in the plugins.txt that I exported from Jenkins... I will have a look.

**Comment by logandonley** [comment]
You may have used this, but if not, I found this handy script on StackOverflow which prints out all the plugins installed and their versions:
```
Jenkins.instance.pluginManager.plugins.sort { it.getDisplayName() }.each{
  plugin -> 
    println ("${plugin.getShortName()}:${plugin.getVersion()}")
}
```

**Comment by InfoSec812** [comment]
Exactly what I used. The problem that I am seeing is that when I deploy
from the ci-cd-starter, the Blue Ocean plugins are not being installed.

Deven Phillips
Senior Consulting Engineer
Red Hat, Open Innovation Labs

**Comment by InfoSec812** [comment]
I performed a diff/merge to bring in the missing items from the previous version, but I still cannot get it to deploy with all of those plugins using the ci-cd-starter, so I don't know if those are all of the correct plugins/versions. Still working through this.

**Comment by InfoSec812** [comment]
Superseded by newer PR

**Pull request closed without merging**
