### PR TITLE
Adds Ability to use LDAP

### LINKED ISSUE #2: Figure out LDAP integration with IdM

### PR DESCRIPTION
**Pull request by mcanoy**
#### What does this PR do?
Closes #2 

#### Which tests illustrate how this code works?
this doesn't have test in this repo but try ansible-stacks cdk_create_pipeline_ldap.yml

#### Is there a relevant Issue open for this?
#2 

#### Are there any other relevant resources that should be reviewed as well?
coincides with ansible-stacks change to environmental variables and pipeline test

#### Who would you like to review this?
/cc @sherl0cks @oybed

### CODE REVIEW

**Comment by sherl0cks** [comment]
@mcanoy does ldap-config.groovy run on s2i assemble or upon pod creation?

**Comment by mcanoy** [comment]
@sherl0cks it runs at jenkins app start. so essentially pod creation. Also no issues running more than once.

**Comment by sherl0cks** [comment]
@mcanoy does that script execution need to complete before Jenkins initialization is complete and it begins accepting login requests?

**Comment by mcanoy** [comment]
Yes. Attached log to show where 

[jenkins.txt](https://github.com/rht-labs/openshift-jenkins-s2i-config/files/554608/jenkins.txt)

**Comment by mcanoy** [comment]
Yes. Attached log. You can see the ldap getting set
[jenkins.txt](https://github.com/rht-labs/openshift-jenkins-s2i-config/files/554609/jenkins.txt)

**Comment by sherl0cks** [comment]
Cool. Thanks for details. Looks good to me.

**Pull request merged**
